### ISSUE TITLE
Adding Agile questions to quiz site

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#103]
### What general issue would you like to create?

[developerquiz.org](developerquiz.org) currently has over 600 quiz questions. We are looking to expand on the agile  questions and we encourage other developers to add their quiz questions to the site.

You can find the complete list of agile questions below.
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/data/agile-quiz.ts

You can add your own questions to the top of that file.
**Please first check to make sure your question doesn't already exist in the file before creating a PR.**

Here is an example format for the questions. 

```
  {
    Question:
      "In a Scrum team, who is responsible for stories estimation?",
    Answer: "The Developers",
    Distractor1: "The Product Owner",
    Distractor2: "The Scrum Master",
    Distractor3: "The Product Owner and the Scrum Master",
    Explanation:
      "According to the Scrum Guide, only members of the development team are allowed to estimate development effort. Neither Scrum Master, nor Product Owner.",
    Link: "https://www.freecodecamp.org/news/scrum-the-hard-parts/",
  },
```
For the `link` field, please make sure to use a freeCodeCamp article, freeCodeCamp YouTube video or official documentation.
If you choose to reference a video, please make sure to include the timestamp for the topic covered.

You can read more about how to create timestamps in this [helpful article](https://www.lifewire.com/link-to-specific-part-of-youtube-video-1616414#). 

There are plenty of freeCodeCamp news articles to pull Agile questions from:
https://www.freecodecamp.org/news/tag/agile/

This issue will not be assigned to anyone and will remain open for multiple contributors. 
**Please do not assign yourself to this issue or close it.**

Happy contributing!

**Comment by GulabSinghSikarwar** [comment]
Added Agile Questions  https://github.com/freeCodeCamp/Developer_Quiz_Site/pull/213

**Comment by jdwilkin4** [comment]
If people have questions about this issue, or questions in general on how to contribute, please use the [GitHub discussions area](https://github.com/freeCodeCamp/Developer_Quiz_Site/discussions). 
It will be easier to track conversations over there 👍

**Comment by jdwilkin4** [comment]
For anyone interested in contributing, please read through the [contributing documentation](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md) first.
