### ISSUE TITLE
Adding Security questions to quiz site

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#104]
### What general issue would you like to create?

[developerquiz.org](developerquiz.org) currently has over 600 quiz questions. We are looking to expand on the security  questions and we encourage other developers to add their quiz questions to the site.

You can find the complete list of security questions below.
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/data/security-quiz.ts

You can add your own questions to the top of that file.
**Please first check to make sure your question doesn't already exist in the file before creating a PR.**

Here is an example format for the questions. 

```
  {
    Question:
      "Which of the following type of Hackers protect civilians and organizations by finding and reporting vulnerabilities in the system?",
    Answer: "White Hat Hackers",
    Distractor1: "Grey Hat Hackers",
    Distractor2: "Black Hat Hackers",
    Distractor3: "Red Hat Hackers",
    Explanation:
      "White Hat Hackers work for organizations as Cybersecurity Engineers, Penetration Testers, etc.  where they perform tasks like ethically hacking the system to find and report vulnerabilities. ",
    Link: "https://www.freecodecamp.org/news/white-hat-black-hat-red-hat-hackers/",
  },
```
For the `link` field, please make sure to use a freeCodeCamp article, freeCodeCamp YouTube video or official documentation.
If you choose to reference a video, please make sure to include the timestamp for the topic covered.

You can read more about how to create timestamps in this [helpful article](https://www.lifewire.com/link-to-specific-part-of-youtube-video-1616414#). 

There are plenty of freeCodeCamp news articles to pull Security questions from:
https://www.freecodecamp.org/news/tag/web-security/
https://www.freecodecamp.org/news/tag/cybersecurity/
https://www.freecodecamp.org/news/tag/information-security/
https://www.freecodecamp.org/news/tag/security/

This issue will not be assigned to anyone and will remain open for multiple contributors. 
**Please do not assign yourself to this issue or close it.**

Happy contributing!

**Comment by suryakapurothu** [comment]
Hello @jdwilkin4 
I'm new here and curious to make a good contribution
Found this repo easy to help 
Do I need to be assigned on this?
Or am I good to fork it and work on?

Please help @jdwilkin4

**Comment by isurumaldeniya** [comment]
@suryakapurothu No need to be assigned. You can fork it and add new question and send PR for merge.

**Comment by suryakapurothu** [comment]
@isurumaldeniya 
[](https://github.com/freeCodeCamp/Developer_Quiz_Site/pull/194)
This is my first PR.
Can you please advise and guide me?
Have I done it the right way?
Anything else that I can improve upon?

**Comment by suryakapurothu** [comment]
[https://github.com/freeCodeCamp/Developer_Quiz_Site/pull/194](url)

**Comment by isurumaldeniya** [comment]
@suryakapurothu Hi I am also new to open source contribution. Let's learn together 😊🙌. One issue I found in your PR is you have changed the others' code (dunno whether it happens due to formatting). It is better if you can just add your code part and don't do any changes on others' codes if there is no issue in them.  Other than that, I don't find any issue in your PR. Happy Coding!😄

**Comment by suryakapurothu** [comment]
@isurumaldeniya How does one know if they are changing someone else's code?
Please elaborate.

**Comment by isurumaldeniya** [comment]
@suryakapurothu If you go to your pull request, there is a tab called **Files Changed**. There you can identify the changes you have done to the file.

**Comment by GulabSinghSikarwar** [comment]
Hey Everyone, I want to work on this issue and have already prepared and made changes in my local repo,  so now how should I proceed further to contribute to this issue?   It would be really helpful if anyone could guide me.

**Comment by suryakapurothu** [comment]
@isurumaldeniya 
I didn't make all the changes it shows.
I'm sure of it.
Is it not showing all the changes made by multiple users?

**Comment by isurumaldeniya** [comment]
> Hey Everyone, I want to work on this issue and have already prepared and made changes in my local repo, so now how should I proceed further to contribute to this issue? It would be really helpful if anyone could guide me.

Hi Gulab,
After making changes you can create a new branch and commit those changes to that branch. And after you push those changes to the github in your forked repo you can see the changes. Then you can send a pull request to the main repo from you branch.

1. make changes to you local repo(add new questions)
2. `git checkout -b <branch-name>`  -- this will create a new branch for you in your local repository.
3. `git add .` -- this will add all the changes you have done.
4. `git commit -m "commit message" `-- commit message can be a meaningful message on what you add. This will commit your changes.
5. `git push --set-upstream origin <branch-name>` -- this will push your local changes to the git hub
6. now send a PR from your forked repo to the main repo using github interface.

Hope all clread for you. Feel free to ask if you need futher calrifications.

**Comment by isurumaldeniya** [comment]
> @isurumaldeniya I didn't make all the changes it shows. I'm sure of it. Is it not showing all the changes made by multiple users?

@suryakapurothu 😄 No worries. Just make sure there are no such changes when you send PR in the future. I think this is most probably due to formatting the code.

**Comment by GulabSinghSikarwar** [comment]
> 5\. git push --set-upstream origin

thanks buddy, for help, but when I am pushing my code and comparing it  is showing   ' there isn't anything to compare '

**Comment by isurumaldeniya** [comment]
@GulabSinghSikarwar Did you commit your changes ?

**Comment by GulabSinghSikarwar** [comment]
@isurumaldeniya  Yes

**Comment by isurumaldeniya** [comment]
@GulabSinghSikarwar did you see your newly created branch in your forked repository?

**Comment by GulabSinghSikarwar** [comment]
yes

**Comment by isurumaldeniya** [comment]
@GulabSinghSikarwar if you follow the steps correctly, you should see the changes you have done locally in the repository in GitHub. 🤔 post some screenshots, maybe we can try and figure something thing out.

**Comment by GulabSinghSikarwar** [comment]
![image](https://user-images.githubusercontent.com/94665834/193813137-78bff69e-f9e0-4397-a06f-3a90275ec146.png)

**Comment by GulabSinghSikarwar** [comment]
![image](https://user-images.githubusercontent.com/94665834/193813695-b178c0ae-8f43-4db9-a1b0-0c864bba3b5a.png)

**Comment by GulabSinghSikarwar** [comment]
on pushing code  and comparing 
![image](https://user-images.githubusercontent.com/94665834/193813929-e5b5525b-7502-42ff-b3d3-b12207f80122.png)

**Comment by jdwilkin4** [comment]
HI @GulabSinghSikarwar ! 

I looked at your forked repo and your branch has two empty commits.
But also your folder structure looks very different than it should in your branch so that is probably why you are having issues.
<img width="431" alt="Screen Shot 2022-10-04 at 6 29 20 AM" src="https://user-images.githubusercontent.com/67210629/193832100-5e44cb52-d141-43a2-b35d-34fb0e02f208.png">

I would suggest updating your main branch first.
<img width="424" alt="Screen Shot 2022-10-04 at 6 30 08 AM" src="https://user-images.githubusercontent.com/67210629/193832284-4bc96f5f-58dc-4899-820b-9b1d27c9d652.png">

Then I would suggest create a new branch off of main and following the steps in the contributing guide.
https://github.com/GulabSinghSikarwar/Developer_Quiz_Site/blob/main/CONTRIBUTING.md#how-to-contribute-and-make-a-pull-request

Hope that helps!

**Comment by GulabSinghSikarwar** [comment]
Thank You  everyone for Supoorting  and provideing help , finally ! i  resolved it  and  have create a PR 
https://github.com/freeCodeCamp/Developer_Quiz_Site/pull/201

**Comment by Nikita0509** [comment]
@jdwilkin4 Hii im a Newbie can u plz guide me, how can i make my first PR. I saw this issue and felt it is easy to get started with.

**Comment by suryakapurothu** [comment]
@Nikita0509 I've started a week ago and trust me this is the right place for a headstart. @jdwilkin4 is a very great mentor.

I'll take this opportunity to let you know how you make your first PR:
Starting,
Create a fork of the freeCodeCamp repository in your local git.
This can be done using the button on the repo page post installing git locally.

**Comment by jdwilkin4** [comment]
If people have questions about this issue, or questions in general on how to contribute, please use the [GitHub discussions area](https://github.com/freeCodeCamp/Developer_Quiz_Site/discussions). 
It will be easier to track conversations over there 👍

**Comment by jdwilkin4** [comment]
For anyone interested in contributing, please read through the [contributing documentation](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md) first.
