### ISSUE TITLE
[General] - want to add more questions to security quiz

### ISSUE THREAD

**Issue by mohitahlawat2001** [freeCodeCamp/Developer_Quiz_Site#1134]
### What general issue would you like to create?

I see that security quiz update a year ago , want to add some new questions

**Comment by jdwilkin4** [comment]
HI @mohitahlawat2001 ! 

All quizzes are open for contribution.

You are free to contribute however many questions you like too 👍 

As a result, I am going to close this issue.

Here is the contributing docs, if you are interested in contributing

https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md
