### ISSUE TITLE
Adding Security questions to quiz site

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/Developer_Quiz_Site#1135]
### What general issue would you like to create?

What general issue would you like to create?

[developerquiz.org](https://github.com/freeCodeCamp/Developer_Quiz_Site/issues/developerquiz.org) currently has over 1500 quiz questions. We are looking to expand on the security questions and we encourage other developers to add their quiz questions to the site.

You can find the complete list of security questions below.
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/data/security-quiz.ts

You can add your own questions to the top of that file.
Please first check to make sure your question doesn't already exist in the file before creating a PR.

Here is an example format for the questions.

```
 {
    Question: "Which of the following is not an Attack model in cryptanalysis?",
    Answer: "CVA (Chosen Vector Attack)",
    Distractor1: "CPA (Chosen Plaintext Attack)",
    Distractor2: "CCA (Chosen Ciphertext Attack)",
    Distractor3: "COA (Ciphertext Only Attack)",
    Explanation: "There is no attack model named CVA (Chosen vector attack).",
    Link: "https://en.wikipedia.org/wiki/Attack_model"
  }
```
For the link field, please make sure to use a freeCodeCamp article, freeCodeCamp YouTube video or official documentation.
If you choose to reference a video, please make sure to include the timestamp for the topic covered.

You can read more about how to create timestamps in this [helpful article](https://www.lifewire.com/link-to-specific-part-of-youtube-video-1616414#).

There are plenty of freeCodeCamp news articles to pull Security questions from:
https://www.freecodecamp.org/news/tag/security

This issue will not be assigned to anyone and will remain open for multiple contributors.
Please do not assign yourself to this issue or close it.

Happy contributing!

**Comment by jdwilkin4** [comment]
Is there a reason why we need a specific issue here?
All quizzes are open for contribution

**Comment by jdwilkin4** [comment]
I will mark this for Hacktoberfest for those interested

**Comment by nitesh2920** [comment]
Raised a pr #1139  please check @jdwilkin4 @a2937

**Comment by tasbi03** [comment]
Hello , I have added Few questions and raised a Pull Request #1140 . can you please check and let me know. @jdwilkin4 @a2937 . Thank You !

**Comment by jdwilkin4** [comment]
@tasbi03 and @nitesh2920 

Please do no ping maintainers for reviews.

We understand that you are excited to contribute but maintainers will get to PR's when they have time.
Thanks for understanding

**Comment by nitesh2920** [comment]
@jdwilkin4 okay sure!

**Comment by srahi904** [comment]
Hello , I have added Few questions and raised a Pull Request , can you please check and let me know.  Thank You !
