### ISSUE TITLE
[Bug] - typescript issue at Quiz modal props (Questions.tsx file)

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/Developer_Quiz_Site#1151]
### looks like 'correct' field is not supplied...

![Image](https://github.com/user-attachments/assets/2b78fd90-b4ec-41a9-9740-1aff90d9b414)

**Comment by VeerChaurasia** [comment]
@shootermv can I take this one?

**Comment by jdwilkin4** [comment]
@VeerChaurasia 

For bug issues, assignment is not necessary.

If you are interested on working on a bug issue, feel free to submit a PR 👍
