### ISSUE TITLE
[General] - Advanced DSA problems

### ISSUE THREAD

**Issue by raj-mistry-01** [freeCodeCamp/Developer_Quiz_Site#1182]
I have seen that no quiz is for data structures which is the most important topic for interview in computer Science

**Hard** only questions for Data Structures And Algorithms

I will also add medium and easy mcqs .

Adding Quiz topic to the repo... 

I hope you will assign this issue to me , under **hacktoberfect** tag , I ensure it will help

**Comment by jdwilkin4** [comment]
> I have seen that no quiz is for data structures

We are going to keep it to just the general cs quiz file.
So if you want to contribute DSA questions, you can add them to that file
Feel free to open a PR. Any PR merged during October counts toward Hacktoberfest
