### ISSUE TITLE
[Docs] - Adding the New Questions To Every Quiz

### ISSUE THREAD

**Issue by raj-mistry-01** [freeCodeCamp/Developer_Quiz_Site#1184]
### What changes would you like to make in the documentation?

I hope you will assign this issue under **hactoberfest** to me , As I will add some few questions to every type of quiz

Thank you , Looking for the further contribution to the repo..

**Comment by jdwilkin4** [comment]
You don't need to open an issue.
You can just create a PR to add your questions to the different quizzes 👍 
Any PR submitted during october counts towards hacktoberfest
