### ISSUE TITLE
[Docs] - Update README with new categories

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#120]
### What changes would you like to make in the documentation?

We recently added some new quiz categories which means our README needs to be updated. 
Here is the README file: https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/README.md

Here is what the current README categories section looks like
```md
- HTML 🖊️
- CSS 🎨
- JavaScript ⚙️
- Linux 🐧
- Python 🐍
- Git 📁
- SQL 📊
- IT 🖥️
- and Computer Science Concepts 🤖
```

Please update the categories section of the README to include these new categories:

- Quality Assurance
- Agile
- Security

You don't need to worry about adding emojis next to these new categories. 

If you are interested in working on this issue, then please comment below and it will be assigned to you.

**Comment by codewithnadeem14502** [comment]
hello sir/mam, i want to contribute to it, can you assign me this issue and i am completely new to open source

**Comment by jdwilkin4** [comment]
Hi @Mustafa-Azad025 ! 

I have assigned it to you since you replied first.

**Comment by jdwilkin4** [comment]
HI @codewithnadeem14502 ! 

This issue has been assigned. 
But we do have 8 other issues open, that are very beginner friendly if you are still interested in contributing.

**Comment by codewithnadeem14502** [comment]
but mam , i have raise the PR please check it

**Comment by jdwilkin4** [comment]
@codewithnadeem14502 

I understand and have seen your PR but @Mustafa-Azad025 did reply first and was assigned this issue.
There will be more beginner issues added later on plus we do have 8 beginner friendly issues already open that will remain open for multiple contributors.

**Comment by Mustafa-Azad025** [comment]
Thanks mam , i will update and raise PR till night and 
will you merge at 1st oct to avail benifit of hacktoberfest?

**Comment by jdwilkin4** [comment]
@Mustafa-Azad025 
If you add the DO NOT MERGE  label on your PR, and leave a comment on your PR about hacktoberfest then I can wait to merge it till October 1st.

**Comment by Mustafa-Azad025** [comment]
oh ,
i haven't read it 😥

**Comment by jdwilkin4** [comment]
I added the label for you

**Comment by Mustafa-Azad025** [comment]
Hey @jdwilkin4 ,
Please Merge Pull Request Of This .
