### ISSUE TITLE
[imporvement] - move colors css rules to colors.css file

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/Developer_Quiz_Site#1215]
### What bug did you find in the codebase?

it can be good to have all colors css rules like backgrounds, border colors, text colors, etc - to be at separate `colors.css` file. 
Also it can be good to define the color values as css variables
like: `--primary: #0a0a23`

**Comment by Bugbuster2004** [comment]
hey @shootermv  i wanted to work on this issue, i find it interesting

**Comment by shootermv** [comment]
Go ahead! Feel free to work on it
