### ISSUE TITLE
[imporvement] - extract all typscript interfaces into common `types` file

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/Developer_Quiz_Site#1216]
### What bug did you find in the codebase?

as far as i can see - there are type definition are located at components files
i think it is better to have all the defiinition at one common file in that way types can be found easily and also - can be  reused

**Comment by jdwilkin4** [comment]
> i think it is better to have all the defiinition at one common file in that way types can be found easily and also - can be reused


I think this depends on if that particular type is only used on one file or not.
If that type is only used once, then I don't see a need to move it to the types file and export it.
But if that type is already being resused in multiple files, then yes it does make sense to have it in one file and export it in the files where it is needed

**Comment by saksham-malhotra-27** [comment]
Hey @shootermv @jdwilkin4 , Is this still on guys ?

**Comment by shootermv** [comment]
I think it is on

**Comment by saksham-malhotra-27** [comment]
Alright ! Can you assign this issue to me ? @shootermv

**Comment by shootermv** [comment]
@saksham-malhotra-27 - i think you can start work on this issue

**Comment by saksham-malhotra-27** [comment]
Okay !!

**Comment by saksham-malhotra-27** [comment]
Hey @shootermv @jdwilkin4 ! 
I’ve consolidated all the interfaces into a single common types file. If there's anything else that needs to be added, let me know!
