### ISSUE TITLE
[Bug] - Unable to Access Image files in Gitpod Environment

### ISSUE THREAD

**Issue by Neha611** [freeCodeCamp/Developer_Quiz_Site#1268]
### What bug did you find in the codebase?

In `Welcome.tsx` file there is error in importing `.webp` images from **images** folder. 
I am using **Gitpod Environment**. 

The error it is showing is -: 

*Cannot find module '../images/rpg-menu.webp' or its corresponding type declarations.*

[![Image](https://github.com/user-attachments/assets/77c541ee-c778-41a8-878f-3fa5cb27164d)](url)

**Comment by jdwilkin4** [comment]
I pushed up a commit to add a `image.d.ts` file which resolved the typescript errors.
