### ISSUE TITLE
Adding JavaScript quiz questions

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#14]
[developerquiz.org](developerquiz.org) currently has over 600 quiz questions. We are looking to expand on the JavaScript questions and we encourage other developers to add their quiz questions to the site.

**Please note: we are only focusing on general JavaScript questions instead of library and framework specific questions.**

You can find the complete list of questions below.
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/data/javascript-quiz.ts

You can add your own questions to the top of that file.
**Please first check to make sure your question doesn't already exist in the file before creating a PR.**

Here is an example format for the questions. 

```
  {
    Question:
      "In JavaScript, what is the name of the method used to remove white space from the beginning and end of a string?",
    Answer: ".trim()",
    Distractor1: ".substring()",
    Distractor2: ".reduce()",
    Distractor3: ".slice()",
    Explanation:
      "The .trim() method removes white space (including space, tab, etc.) from both ends of a string and returns a new string without modifying the original.",
    Link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim",
  },
```
For the `link` field, please make sure to use a freeCodeCamp article, freeCodeCamp YouTube video or official documentation.
If you choose to reference a video, please make sure to include the timestamp for the topic covered.

You can read more about how to create timestamps in this [helpful article](https://www.lifewire.com/link-to-specific-part-of-youtube-video-1616414#). 

This issue will not be assigned to anyone and will remain open for multiple contributors. 
**Please do not assign yourself to this issue or close it.**

Happy contributing!

**Comment by ashutosh-mishra4** [comment]
Hey, @jdwilkin4 Could you please assign this issue to me? I want to contribute to it this weekend.

**Comment by jdwilkin4** [comment]
Hi @ashutosh-mishra4 ! 
Any issue with the help wanted or good first issue labels are up for grabs.
Also, this particular issue will remain open so multiple developers can continually add their javascript questions over time. 
Happy contributing!

**Comment by Prathamesh-Shaniware** [comment]
Hey, I would like to contribute. Can you please assign this to me?

**Comment by jdwilkin4** [comment]
Hi @Prathamesh-Shaniware ! 

This issue isn't going to be assigned to anyone.
This issue will remain open for anyone who wants to contribute.
Any issue marked with Help wanted or Good first issue is up for grabs.

**Comment by atharvagarwal** [comment]
I would like to add questions about the Event Loop

**Comment by nishtha53** [comment]
@jdwilkin4 I want to add more questions please assign to me.

**Comment by jdwilkin4** [comment]
@nishtha53 

This issue isn't going to be assigned to anyone.
This issue will remain open for anyone who wants to contribute.
Any issue marked with Help wanted or Good first issue is up for grabs.

**Comment by nishtha53** [comment]
okk thankyou

**Comment by jdwilkin4** [comment]
If people have question about this issue, or questions in general on how to contribute, please use the [GitHub discussions area](https://github.com/freeCodeCamp/Developer_Quiz_Site/discussions). 
It will be easier to track conversations over there 👍

**Comment by jdwilkin4** [comment]
For anyone interested in contributing, please read through the [contributing documentation](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md) first.
