### ISSUE TITLE
Adding Python quiz questions

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#15]
[developerquiz.org](developerquiz.org) currently has over 600 quiz questions. We are looking to expand on the Python questions and we encourage other developers to add their quiz questions to the site.

**Please note: we are only focusing on general Python questions instead of library and framework specific questions.**

You can find the complete list of questions below.
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/data/python-quiz.ts

You can add your own questions to the top of that file.
**Please first check to make sure your question doesn't already exist in the file before creating a PR.**

Here is an example format for the questions. 

```
  {
    Question:
      "In Python, which method can be used to replace parts of a string?",
    Answer: "replace()",
    Distractor1: "switch()",
    Distractor2: "repl()",
    Distractor3: "find()",
    Explanation:
      "If you need to search through a string for a pattern, and replace it with another pattern, you can use the replace() method.",
    Link: "https://www.freecodecamp.org/news/python-string-methods-tutorial-how-to-use-find-and-replace-on-python-strings/",
  },
```
For the `link` field, please make sure to use a freeCodeCamp article, freeCodeCamp YouTube video or official documentation.
If you choose to reference a video, please make sure to include the timestamp for the topic covered.

You can read more about how to create timestamps in this [helpful article](https://www.lifewire.com/link-to-specific-part-of-youtube-video-1616414#). 

This issue will not be assigned to anyone and will remain open for multiple contributors. 
**Please do not assign yourself to this issue or close it.**

Happy contributing!

**Comment by Still11** [comment]
{
    Question: "We have a python list a = [1,2,3,4,5,6,7,8,9] what is the output of a[-1:-5:-1]?",
    Answer: "[9, 8, 7, 6]",
    Distractor1: "[9, 8, 7, 6, 5]",
    Distractor2: "[4, 3, 2, 1]",
    Distractor3: "[1, 2, 3, 4]",
    Explanation: "The slicing syntax for the list is [a:b:c]. Here a and b are start and end indexes. The ‘c’ is the step value.",
    Link: "https://www.freecodecamp.org/news/python-lists-detailed-visual-introduction/",
  },

**Comment by jdwilkin4** [comment]
Hi @Still11 ! 

If you are interested in contributing a quiz question, then please create a PR.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
Thanks!

**Comment by suryakapurothu** [comment]
Hey @Still11,
A wonderful question there.
If you need help creating a PR for the same, we can team up and work on things.

**Comment by KmKalpana** [comment]
Hii, Can I contribute in the python quiz questions.

**Comment by Sin-Sumit** [comment]
@jdwilkin4 what do you mean by distractors?

**Comment by suryakapurothu** [comment]
@Sin-Sumit Distractors are options other thank the right answer that appear as choices under the question.
The imply that the corresponding items are incorrect answers for the question.

**Comment by jdwilkin4** [comment]
If people have question about this issue, or questions in general on how to contribute, please use the [GitHub discussions area](https://github.com/freeCodeCamp/Developer_Quiz_Site/discussions). 
It will be easier to track conversations over there 👍

**Comment by jdwilkin4** [comment]
For anyone interested in contributing, please read through the [contributing documentation](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md) first.
