### ISSUE TITLE
Adding Linux quiz questions

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#16]
[developerquiz.org](developerquiz.org) currently has over 600 quiz questions. We are looking to expand on the Linux questions and we encourage other developers to add their quiz questions to the site.

You can find the complete list of questions below.
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/data/linux-quiz.ts

You can add your own questions to the top of that file.
**Please first check to make sure your question doesn't already exist in the file before creating a PR.**

Here is an example format for the questions. 

```
  {
    Question: "In Linux, what is a maximum length for a filename?",
    Answer: "255 Bytes",
    Distractor1: "225 Bytes",
    Distractor2: "235 Bytes",
    Distractor3: "295 Bytes",
    Explanation:
      "The maximum length for a file name is 255 bytes. The maximum combined length of both the file name and path name is 4096 bytes.",
    Link: "https://www.ibm.com/docs/en/spectrum-protect/8.1.9?topic=parameters-file-specification-syntax",
  },
```
For the `link` field, please make sure to use a freeCodeCamp article, freeCodeCamp YouTube video or official documentation.
If you choose to reference a video, please make sure to include the timestamp for the topic covered.

You can read more about how to create timestamps in this [helpful article](https://www.lifewire.com/link-to-specific-part-of-youtube-video-1616414#). 

This issue will not be assigned to anyone and will remain open for multiple contributors. 
**Please do not assign yourself to this issue or close it.**

Happy contributing!

**Comment by a2937** [comment]
Can questions regarding with what XWindows and GNOME are be added to the question pool? Like XWindows being the  and GNOME being a popular desktop option for Linux flavors. 
Sources: 
https://www.x.org/wiki/guide/concepts/
https://www.gnome.org/

**Comment by jdwilkin4** [comment]
@a2937 
Sure, that would fine

**Comment by GulabSinghSikarwar** [comment]
Added Few Linux Questions  https://github.com/freeCodeCamp/Developer_Quiz_Site/pull/215

**Comment by jdwilkin4** [comment]
If people have questions about this issue, or questions in general on how to contribute, please use the [GitHub discussions area](https://github.com/freeCodeCamp/Developer_Quiz_Site/discussions). 
It will be easier to track conversations over there 👍

**Comment by jdwilkin4** [comment]
For anyone interested in contributing, please read through the [contributing documentation](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md) first.
