### ISSUE TITLE
Adding SQL quiz questions

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#17]
[developerquiz.org](developerquiz.org) currently has over 600 quiz questions. We are looking to expand on the SQL questions and we encourage other developers to add their quiz questions to the site.

You can find the complete list of questions below.
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/data/sql-quiz.ts

You can add your own questions to the top of that file.
**Please first check to make sure your question doesn't already exist in the file before creating a PR.**

Here is an example format for the questions. 

```
  {
    Question:
      "Which of the following relational database management systems (RDBMS) should never be used to store data in a production app?",
    Answer: "Microsoft Access",
    Distractor1: "Microsoft SQL Server",
    Distractor2: "MongoDB",
    Distractor3: "PostgreSQL",
    Explanation:
      "Microsoft Access does not offer as much security, availability, and stability as SQL Server.",
    Link: "https://en.wikipedia.org/wiki/Microsoft_Access",
  },
```
For the `link` field, please make sure to use a freeCodeCamp article, freeCodeCamp YouTube video or official documentation.
If you choose to reference a video, please make sure to include the timestamp for the topic covered.

You can read more about how to create timestamps in this [helpful article](https://www.lifewire.com/link-to-specific-part-of-youtube-video-1616414#). 

This issue will not be assigned to anyone and will remain open for multiple contributors. 
**Please do not assign yourself to this issue or close it.**

Happy contributing!

**Comment by erictleung** [comment]
Some places to get questions from:

- https://www.edureka.co/blog/interview-questions/sql-interview-questions
- https://www.geeksforgeeks.org/sql-interview-questions/
- https://intellipaat.com/blog/interview-question/sql-interview-questions/
- https://mindmajix.com/sql-interview-questions
- https://www.toptal.com/sql/interview-questions

**Comment by jdwilkin4** [comment]
Hi @erictleung ! 

Even though these are respected tech blogs, we do also have to remember that we are competing with them in terms of google search rankings. 
The goal is to have our projects promote our publication articles, youtube videos or official documentation over competing publications. 
There is nothing wrong with those tech sites, but we also don't want to be providing them with more traffic to their sites.

So that's why we limit the scope of these questions to just our material or official docs. 👍

**Comment by erictleung** [comment]
@jdwilkin4 makes sense, thanks! That makes sense. I was thinking it is a place to get ideas for questions, but definitely link to freeCodeCamp resources when possible :+1:

**Comment by raykotab** [comment]
Hi! I am trying to make my first contribution and I wonder:
Would a question about the NOW() SQL function be appropriate or too advanced in this case?

**Comment by jdwilkin4** [comment]
Hi @raykotab ! 

I think that question would work since the function returns the date and time.
I don't think it would be too advanced.

**Comment by raykotab** [comment]
Wonderful! Then i'll try my luck with my first PR.

**Comment by GulabSinghSikarwar** [comment]
@jdwilkin4  , I have added a few SQL questions. for this issue  https://github.com/freeCodeCamp/Developer_Quiz_Site/pull/203,

**Comment by Ishukumarpathak** [comment]
Hello
loved to contribute on this repository.
Can you please assign me .

**Comment by jdwilkin4** [comment]
@Ishukumarpathak 
This issue will not be assigned to anyone and will remain open for multiple contributors.
If you are interested in contributing, read through the contributing docs and create a PR with your questions 👍

**Comment by J-ell** [comment]
Is it possible to add multi-choice question? and if yes what is the format?

**Comment by jdwilkin4** [comment]
@J-ell 

Well the website is already following a multiple choice format
<img width="900" alt="Screen Shot 2022-10-12 at 9 32 50 PM" src="https://user-images.githubusercontent.com/67210629/195502251-901f41a0-fb11-4780-b42b-915f9580421b.png">

Can you explain more on what you mean by multiple choice?

**Comment by J-ell** [comment]
I mean questions with more than one answers. for example:
In git which of the following syntax is used to add changes to the staging area or indexed? select all that apply 
(a) git add file.txt
(b) git add .
(c) git mv file.txt
(d) git add
where the answer is both a and b

**Comment by jdwilkin4** [comment]
@J-ell 

In that situation you would just write out "Both git add filename and git mv filename"

Our design doesn't support adding A), B), C) D) in front of the answers since we are just using buttons. 👍

**Comment by jdwilkin4** [comment]
If people have questions about this issue, or questions in general on how to contribute, please use the [GitHub discussions area](https://github.com/freeCodeCamp/Developer_Quiz_Site/discussions). 
It will be easier to track conversations over there 👍

**Comment by jdwilkin4** [comment]
For anyone interested in contributing, please read through the [contributing documentation](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md) first.
