### ISSUE TITLE
[Bug] - Add a media query to the "Get started(it's free)" button

### ISSUE THREAD

**Issue by Ryukemeister** [freeCodeCamp/Developer_Quiz_Site#176]
### What bug did you find in the codebase?

- The size of the Get started button remains with a  width of 400px even for small screen devices having a width of 360px or 375px which is breaking the page.
-  The current screen looks like this

![Before](https://user-images.githubusercontent.com/86043008/193562904-b1915203-877d-4d15-a42a-074f0d81bc7a.jpg)

- I'd like to add a media query to the button so that its size shrinks in case of small screen devices.
 
![After](https://user-images.githubusercontent.com/86043008/193563152-76ff005e-fac6-4837-bcf4-9ab751b84e27.jpg)

- Also there is a width problem regarding mobile devices which is caused by class "content-row-container".
- The class "content-row-container" is having a -12px margin even if I try to set its width to 100vw which is causing an issue so please look into it.

**Comment by jdwilkin4** [comment]
HI @Ryukemeister ! 

Thank you for brining up this bug. 

If you are interested in working on this issue, then we can assign it to you. Otherwise we can open up this issue to other contributors.

**Comment by Ryukemeister** [comment]
Hi @jdwilkin4, yes I'd like to work on this issue. Please assign it to me.
