### ISSUE TITLE
Adding Accessibility questions to quiz site

### ISSUE THREAD

**Issue by YuriDevAT** [freeCodeCamp/Developer_Quiz_Site#260]
### What feature would you like to see?

It would be great having accessibility questions on the quiz site to spread awareness on the importance of web accessibility.

**Comment by jdwilkin4** [comment]
Hi @YuriDevAT ! 

I think that would be a good idea.
Let me double check with Quincy to see if he is interested in adding this category now to both the quiz site and Learn to Code RPG game.

**Comment by jdwilkin4** [comment]
This category was approved.
I am going to close this issue and create a new one with details on how people can contribute accessibility quiz questions.

**Comment by YuriDevAT** [comment]
Thank you for your respond @jdwilkin4! Happy to hear that.
