### ISSUE TITLE
Adding Computer Science Questions

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#29]
[developerquiz.org](developerquiz.org) currently has over 600 quiz questions. We are looking to expand on the Computer Science questions and we encourage other developers to add their quiz questions to the site.

You can find the complete list of questions below.
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/data/general-cs-quiz.ts

You can add your own questions to the top of that file.
**Please first check to make sure your question doesn't already exist in the file.**

Here is an example of one of the current CS questions.

```
 {
    Question: "Which one of these is NOT a common time complexity equation for BigO notation?",
    Answer: "O(n14)",
    Distractor1: "O(1)",
    Distractor2: "O(log n)",
    Distractor3: "O(n)",
    Explanation: "O(1), O(log n), O(n) are just some of the common time complexity equations for BigO notation.",
    Link: "https://www.youtube.com/watch?v=zg9ih6SVACc&t=867s",
  },
```
For the link field, please make sure to use a freeCodeCamp article, or freeCodeCamp YouTube video.
If you choose to reference a video, please make sure to include the timestamp for the topic covered.

Here is an example of a timestamp video for BigO notation
https://www.youtube.com/watch?v=zg9ih6SVACc&t=867s

You can read more about how to create timestamps in this [helpful article](https://www.lifewire.com/link-to-specific-part-of-youtube-video-1616414#). 

**Please note: Do not close this issue.** We want to keep this issue open for multiple contributors.

Happy contributing!

**Comment by Kas1680** [comment]
Is this repo still active?

**Comment by jdwilkin4** [comment]
Yes it is

**Comment by a2937** [comment]
Can a question like what the HTML abbreviation stands for be added to the pool of questions?

**Comment by jdwilkin4** [comment]
@a2937 
I ran a search in the `full-quiz.ts` and there is already a question for the abbreviation of HTML on line 6566.

But the question should be modified because the current answer says  
Answer: "Hyper Text Markup Language",

But it should say 
Answer: "HyperText Markup Language",

But in general, it is always best to check the list of questions first to see if it exists so we don't create duplicate questions.

Hope that helps!

**Comment by a2937** [comment]
I wanna update an distraction answer to be "Friend Function" instead of "Friend functiom" ; as soon as I can think of an proper question involving template strings.

**Comment by Aman0786-git** [comment]
@jdwilkin4 Hello Sir I have added two CS quiz questions , Can you please help me out I am not able to do pull request.
This is my first open source contribution.Thank You

**Comment by Aman0786-git** [comment]
@jdwilkin4  Hello Ma'am I have added two CS quiz questions .I had pushed the changes but can you please help me out with pull request.
This is my first open source contribution.Thank You.

**Comment by jdwilkin4** [comment]
Hi @Aman0786-git ! 

I think it would be best if you post your question, with the results you are getting in the terminal in the freeCodeCamp forum so we can get a better idea of what the issue is. We will be able to better assist you there. 

https://forum.freecodecamp.org/

**Comment by jdwilkin4** [comment]
@Aman0786-git 

You can also read through this helpful article on how to create pull requests
https://opensource.com/article/19/7/create-pull-request-github

**Comment by anp-scp** [comment]
For the attribute "link", can we add link to Wikipedia articles?

**Comment by jdwilkin4** [comment]
If people have questions about this issue, or questions in general on how to contribute, please use the [GitHub discussions area](https://github.com/freeCodeCamp/Developer_Quiz_Site/discussions). 
It will be easier to track conversations over there 👍

**Comment by jdwilkin4** [comment]
For anyone interested in contributing, please read through the [contributing documentation](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md) first.
