### ISSUE TITLE
Adding ReactJS Quiz Questions

### ISSUE THREAD

**Issue by KmKalpana** [freeCodeCamp/Developer_Quiz_Site#303]
### What feature would you like to see?

Hii, Can I add the quiz questions Regarding Reactjs.

**Comment by jdwilkin4** [comment]
Hi @KmKalpana ! 

At this time, we are not opening up questions for JavaScript libraries or frameworks. 
We are mainly concerned with filling questions in the existing categories which will also be used in the Learn to Code RPG game. 
Once we get healthy of amounts of questions across the board for the existing categories, then we will revisit the discussions on opening up to new categories and which ones those will be. 👍
