### ISSUE TITLE
[Bug] - Missing answer for JavaScript question

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#399]
### What bug did you find in the codebase?

It looks like we have a missing answer for this JavaScript question.

<img width="1013" alt="Screen Shot 2022-10-15 at 2 50 46 PM" src="https://user-images.githubusercontent.com/67210629/196008886-27724162-4a35-45d1-bf3e-9c5cf2be3d4f.png">

I would also like to change the distractor options. 

Here is the fix I am looking for.
```
  {
    Question: "In JavaScript, what will the following code return: typeof a?",
    Answer: "undefined",
    Distractor1: "string",
    Distractor2: "object",
    Distractor3: "number",
    Explanation:
      "In JavaScript, if you use the typeof operator on an undeclared variable then it will return undefined. ",
    Link: "https://www.freecodecamp.org/news/javascript-typeof-how-to-check-the-type-of-a-variable-or-object-in-js/",
  },
```

This question is located in the JavaScript quiz here:
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/data/javascript-quiz.ts

Please read through the contributing documentation first
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/c2896c9957c075f3bab7801f7576f9766d8f161d/CONTRIBUTING.md

If you are interested in working on this issue, please reply asking to be assigned.
**Please note: this issue will only be assigned on a first come basis and will only be assigned to those who are new to the Developer Quiz site**

**Comment by lizwe-mac** [comment]
Hi @jdwilkin4 I'm interested in this FTO

**Comment by jdwilkin4** [comment]
The issue has been assigned to you. 👍
