### ISSUE TITLE
[Docs] - typo in javascript question

### ISSUE THREAD

**Issue by LeGrandMAG** [freeCodeCamp/Developer_Quiz_Site#622]
### What changes would you like to make in the documentation?

The is a typo in the Javascript question about querySelector().
![image](https://user-images.githubusercontent.com/64711820/199099232-cfe25fb3-3080-4aaf-97fc-fa4e50c876dc.png)

Instead of "one of more", it should be "one or more"....

I would be glad to work on this issue.

**Comment by jdwilkin4** [comment]
I assigned the issue to you.
But I also added a title for this issue.
When creating issues, it is important to always include a title so we know the context.
