### ISSUE TITLE
[Feature] - Spell checking for the data files

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/Developer_Quiz_Site#632]
### What feature would you like to see?

We are going to be using spellchecker-cli with husky to check to see if all the words are spelled correctly prior to committing. I don't know if there are any remaining flaws in their dependencies' or dependencies' dependencies but I will keep my eyes peeled.

**Comment by a2937** [comment]
Can we put this on hold till the developers behind Spell-checker CLI fix their punctuation issue?

**Comment by jdwilkin4** [comment]
Sure. You can just close the draft PR you have and then open it again later.

**Comment by a2937** [comment]
It'll be a while before this issue is ready to be tackled.
