### ISSUE TITLE
Add 10 more correct responses to the correctModalResponses array

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#669]
### What general issue would you like to create?

Inside the `/src/data/modal-responses.ts` file there is a `correctModalResponses` array filed with responses for when a user gets the question correct.

<img width="500" alt="Screenshot 2023-09-07 at 12 50 40 PM" src="https://github.com/freeCodeCamp/Developer_Quiz_Site/assets/67210629/3979a00e-28be-4475-9c01-4c7be73cac95">

It would be nice to add 10 more responses to the `correctModalResponses`
Please keep your responses to 20 characters or less. 

This issue will be assigned to the first person who replies back to the issue asking for assignment. 

If you are a first time contributor, then please read through the [Code of conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/33cb22f327fc17e57a0d85e59082c4c8d467f67b/CODE_OF_CONDUCT.md) and [Contributing](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/33cb22f327fc17e57a0d85e59082c4c8d467f67b/CONTRIBUTING.md) docs first

**Comment by mustachemo** [comment]
hello i would like this issue please, but can you elaborate on what the issue is?

**Comment by jdwilkin4** [comment]
HI @mustachemo ! 

The issue has been assigned to you.

For this issue, it would be best to use the app first so you better understand the issue. 👍 
But the summary of it as that, when a user answers a question, a modal pops up telling them if the answer is correct or not. 
It will display some sort of response like "Correct" or "Good job" when you get an answer correct. 

This issue about adding more responses to the `correctModalResponses` array in the codebase. 

Hope that helps!

**Comment by jdwilkin4** [comment]
@Gautam-Hegde 
assigning you to this issue
