### ISSUE TITLE
Update grammar and code examples for JS arrow function question

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#670]
### What general issue would you like to create?

I want to update the grammar and code examples for the following question in the `/src/data/javascript-quiz.ts` file

## Current question
```
  {
    Question:
      "In JavaScript, select the right syntax for an ES6 arrow function:",
    Answer: "let variable = () => {//code block}",
    Distractor1: "let variable => (){//code block}",
    Distractor2: "let variable = function() => {//code block}",
    Distractor3: "let variable = function(){//code block}",
    Explanation:
      "ES6 arrow functions provide you with an alternative way to write shorter syntax compared to the traditional function expression.",
    Link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions"
  },
```
## Proposed change I would like implemented

```
  {
    Question: "Select the correct syntax for a JavaScript ES6 arrow function:",
    Answer: "const variable = () => // code",
    Distractor1: "const variable <=> ()()// code ",
    Distractor2: "const variable === function() => {//code}",
    Distractor3: "const variable =>> function(){//code}",
    Explanation:
      "ES6 arrow functions provide you with an alternative way to write shorter syntax compared to the traditional function expression.",
    Link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions"
  },
```

This issue will be assigned to the first person who replies back to the issue asking for assignment.

If you are a first time contributor, then please read through the [Code of conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/33cb22f327fc17e57a0d85e59082c4c8d467f67b/CODE_OF_CONDUCT.md) and [Contributing](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/33cb22f327fc17e57a0d85e59082c4c8d467f67b/CONTRIBUTING.md) docs first

**Comment by kristenking** [comment]
@jdwilkin4 Could I be assigned for this issue or should we wait for jgeev to work on it? Thank you

**Comment by jdwilkin4** [comment]
The issue has been assigned to you @kristenking
