### ISSUE TITLE
Update grammar for JS question on nullish coalescing operator

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#671]
### What general issue would you like to create?

I want to cleanup the JS question on the nullish coalescing operator found in the `/src/data/javascript-quiz.ts` file

## Current implementation
```
 {
    Question:
      "In JavaScript, what will be the value of output? let output = null ?? 20",
    Answer: "20",
    Distractor1: "undefined",
    Distractor2: "null",
    Distractor3: "Syntax error",
    Explanation:
      "The nullish coalescing operator in JavaScript will return the right-hand side operand if the left-hand side operand is null or undefined.",
    Link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator"
  },
```
## Proposed change I wanted implemented 

```
  {
    Question:
      "In JavaScript, what will be the value for the following code: null ?? 20",
    Answer: "20",
    Distractor1: "undefined",
    Distractor2: "null",
    Distractor3: "Syntax error",
    Explanation:
      "The nullish coalescing operator in JavaScript will return the right-hand side operand if the left-hand side operand is null or undefined.",
    Link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator"
  },
```

This issue will be assigned to the first person who replies back to the issue asking for assignment.

If you are a first time contributor, then please read through the [Code of conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/33cb22f327fc17e57a0d85e59082c4c8d467f67b/CODE_OF_CONDUCT.md) and [Contributing](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/33cb22f327fc17e57a0d85e59082c4c8d467f67b/CONTRIBUTING.md) docs first

**Comment by mustachemo** [comment]
Hello, can i be assigned to this please? Also, I am not sure what the difference is between the current and your proposed implementation

**Comment by jdwilkin4** [comment]
Hi @mustachemo ! 

The issue has been assigned to you.

The difference lies in the subtle change in the question itself

Hope that helps
