### ISSUE TITLE
Cleanup JS question on toFixed method 

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#672]
### What general issue would you like to create?

I want to cleanup this question a little bit so it is easier to read.
You can find this question in the `/src/data/javascript-quiz.ts` file

## Current implementation
```
  {
    Question:
      "In JavaScript, if let n = 12345.6789, then what will be the result for console.log(n.toFixed())?",
    Answer: "12346",
    Distractor1: "12345",
    Distractor2: "12345.6789",
    Distractor3: "Undefined. toFixed() must take parameters",
    Explanation:
      "Parameters are optional. If not passed, it will round the given number, leaving with no fractional part",
    Link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed#examples"
  },
```

## Proposed change I wanted implemented

```
  {
    Question:
      "In JavaScript, what will be the result for the following code: 12345.6789.toFixed()?",
    Answer: "12346",
    Distractor1: "12345",
    Distractor2: "12345.6789",
    Distractor3: "Undefined. toFixed() must take parameters",
    Explanation:
      "Parameters are optional. If not passed, it will round the given number, leaving with no fractional part",
    Link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed#examples"
  },

```
This issue will be assigned to the first person who replies back to the issue asking for assignment.

If you are a first time contributor, then please read through the [Code of conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/33cb22f327fc17e57a0d85e59082c4c8d467f67b/CODE_OF_CONDUCT.md) and [Contributing](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/33cb22f327fc17e57a0d85e59082c4c8d467f67b/CONTRIBUTING.md) docs first

**Comment by kristenking** [comment]
Hello @jdwilkin4 , could I work on this issue please?

**Comment by jdwilkin4** [comment]
Hi @kristenking !

The issue has been assigned to you
