### ISSUE TITLE
Duplicate JavaScript quiz question

### ISSUE THREAD

**Issue by kristenking** [freeCodeCamp/Developer_Quiz_Site#679]
### Issue Description
@jdwilkin4 I've noticed that there is a duplicate quiz question in the JavaScript questions list on lines 1596 and 1606.

```
{
  "Question": "In JavaScript, what type of value is an Array?",
  "Answer": "Object",
  "Distractor1": "Array",
  "Distractor2": "Map",
  "Distractor3": "Set",
  "Explanation": "In JavaScript besides primitives types, we have the Object value type. Arrays are a special type of object that represents a collection of similar types of values.",
  "Link": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array"
}

```

### Steps to Reproduce
1. Open the `javascript-quiz.ts`.
2. Navigate to lines 1596 and 1606.

### Expected Behavior
Each question in the quiz should be unique.

### Actual Behavior
The question on line 1596 is identical to the one on line 1606.

### Suggested Fix
Remove one of the duplicate questions.

**Comment by jdwilkin4** [comment]
Hi @kristenking ! 

Thank you for catching this.
I have made this issue available for assignment

**Comment by jdwilkin4** [comment]
@Gautam-Hegde
