### ISSUE TITLE
[Docs] - Remove duplicate mention of checklist in PR template

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#682]
### What changes would you like to make in the documentation?

In the [pull request template](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/.github/PULL_REQUEST_TEMPLATE.md), we need to remove the first mention of checklist that occurs just above the Summary of changes

Here is a screenshot of the word needed to be removed below

<img width="316" alt="Screenshot 2023-09-18 at 12 50 33 PM" src="https://github.com/freeCodeCamp/Developer_Quiz_Site/assets/67210629/daeba026-ce0c-44cd-bb73-cb523e0b06c6">

**Comment by CaioCintra** [comment]
Its just remove the word, right? Can I do that?

**Comment by jdwilkin4** [comment]
@CaioCintra 
Yes that is correct
