### ISSUE TITLE
Remove HTML question for deprecated marquee tag

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#689]
### What general issue would you like to create?

We only want to include questions for active HTML elements.
Let's remove this question on the marquee tag

Here is the file that will need to be edited and here is the question that needs to be removed. 
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/data/html-quiz.ts#L1663C4-L1673

## How to Contribute

Please read through our [Contributing docs](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md)

This issue is available for assignment only. 
If you are interested in working on this issue, please reply back that you wish to be assigned.
Assignment will be given on a first come basis.
We will only accept PR’s with the person assigned to the issue.

Happy hacking!

**Comment by Baburao-sanivada** [comment]
Hello I Want to Work on this issue

**Comment by jdwilkin4** [comment]
it's all yours @Baburao-sanivada 👍

**Comment by Baburao-sanivada** [comment]
Here I should the remove that Piece of Code right?

**Comment by jdwilkin4** [comment]
Yes, you will need to remove that question from the HTML questions object

**Comment by Baburao-sanivada** [comment]
Please check the Pull Request
