### ISSUE TITLE
Enhancement: Categories 

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/Developer_Quiz_Site#69]
**Describe the bug**
Categories would be absolutely amazing to add for the question set. Each question can have one more or category.   

**Expected behavior**
Before you reach the question amount screen, you get to select the category (or categories) that 
questions will be drawn from. Each category is toggle-able and there is two buttons. One for all and one for none. 
You cannot proceed without setting at least one category. The categories would then be passed into the question amount chooser. Retrieved questions will be filtered to match the categories. 

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Firefox

**Additional context**
I'd love to try to tackle this enhancement with some guidance on the layout please.

**Comment by jdwilkin4** [comment]
The issue we face with the categories is the categories are not evenly matched in the amount of questions.
Some categories like html and css have hundreds of questions while other have as little as 10 like the cs section.
That is why we have these open issues in hopes to beef up the category questions.
The community has added some questions to JS section but we are still really light in other areas. 

If we did categories now, then we would have to cap the amount of questions to 10.
That would mean getting rid of the amount screen and providing the user a random list of 10 questions from that category.
