### ISSUE TITLE
Update question on HTML checkboxes

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#691]
### What general issue would you like to create?

I would like to update the question here
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/data/html-quiz.ts#L508-L518

## original question
In HTML, what attribute should you add to <input> to create a checkbox?

## revised question
In HTML, which attribute is used in the input element to create a checkbox? 

## How to Contribute

Please read through our [Contributing docs](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/CODE_OF_CONDUCT.md)

This issue is available for assignment only. 
If you are interested in working on this issue, please reply back that you wish to be assigned.
Assignment will be given on a first come basis.
We will only accept PR’s with the person assigned to the issue.

Happy hacking!

**Comment by Anish-Sarawgi** [comment]
Hey @jdwilkin4, can i work on this issue?

**Comment by jdwilkin4** [comment]
@Anish-Sarawgi its all yours

**Comment by Anish-Sarawgi** [comment]
Hey @jdwilkin4, i have made the required changes. Please have a look.
