### ISSUE TITLE
[Feature] - Addition of Confetti Animation for Perfect Scores🚀

### ISSUE THREAD

**Issue by Gautam-Hegde** [freeCodeCamp/Developer_Quiz_Site#707]
## Description
I would like to request the addition of a confetti animation to the Developer Quiz site. This feature aims to enhance the user experience and celebrate the achievements of users who achieve a perfect score in the quiz.

**Detailed Description:**
Currently, the site provides a point-based scoring system where users can earn points based on their quiz performance. When a user achieves a perfect score (earning all possible points). To make this achievement more engaging and appealing, I propose the addition of a confetti animation that triggers when a user achieves a perfect score.

Here's how the feature would work:
1. When a user completes the quiz and scores a perfect 100% (or the maximum achievable score), a confetti animation will be displayed on the results page to celebrate their achievement.
2. The confetti animation should run for a short duration, approximately 5 seconds, to provide a brief but enjoyable celebration without disrupting the user experience.

**Implementation Considerations:**
- The confetti animation can be implemented using libraries or components designed for this purpose, such as `react-confetti`.
- Ensure that the animation does not affect the overall performance or user experience negatively.

**If approved, I am keen on implementing this feature.**

**Comment by jdwilkin4** [comment]
sounds reasonable to me.
It's been assigned to you
