### ISSUE TITLE
[Feature] -  Proposal for Back Button Enhancement

### ISSUE THREAD

**Issue by CompetitiveRohan** [freeCodeCamp/Developer_Quiz_Site#718]
### What feature would you like to see?

Subject: Proposal for Back Button Enhancement

Dear freeCodeCamp Team,

I hope this message finds you well. I would like to propose an enhancement to our platform.

I suggest adding a back button functionality. This feature would prove exceptionally valuable, especially in scenarios where a participant has progressed beyond the initial question and wishes to return to the page where they selected the number of questions, as opposed to navigating back one question at a time.

Specifically, I envision the back button offering participants the convenience of returning to the question selection page, streamlining their experience and providing greater control over their navigation within the platform.

I am confident in my ability to implement this feature effectively. If you find this proposal aligns with our objectives, I would be enthusiastic about taking on this task and working towards its successful implementation.

I eagerly await your feedback and guidance on this proposal.

Best regards,
Rohan

**Comment by Gautam-Hegde** [comment]
Kindly offer sufficient context or provide a thorough description; otherwise, it may be marked as spam.

**Comment by CompetitiveRohan** [comment]
Currently, our platform lacks a convenient way for participants to navigate back to the page where they selected the number of questions for a quiz. This can be especially frustrating when participants are several questions into a quiz and wish to adjust their preferences.

To address this issue, I suggest adding a back button functionality. This feature would provide participants with the ability to return to the question selection page directly, eliminating the need to navigate back one question at a time.

The benefits of this enhancement are twofold:
1. Improved User Experience: Participants will have greater control over their navigation within the platform, resulting in a smoother and more user-friendly experience.
2. Efficiency: Users can quickly modify their quiz settings without the need to backtrack through multiple questions.

I am confident in my ability to implement this feature effectively. If you find this proposal aligns with our objectives, I would be enthusiastic about taking on this task and working towards its successful implementation.

I understand the importance of context in making informed decisions, and I'm available to provide additional details or discuss any questions you may have. Your feedback and guidance on this proposal would be greatly appreciated.

**Comment by jdwilkin4** [comment]
HI @CompetitiveRohan ! 

It sounds like you are interested in creating more of a return to number of questions button instead of a back button since it would return to the question length selection page and reset the quiz instead of go back one quiz question.
Is that correct?

If so, it might be better to go back to the category selection instead

Also, there should be a modal that pops up to ask users in the middle of the quiz if they are interested in resetting and returning to the category selection page

**Comment by CompetitiveRohan** [comment]
Yes, I think this would be better. Like upon clicking the `back` button, they will return to category selection page and ofc will add a confirmation pop up to confirm if they really want to reset and start again.

**Comment by jdwilkin4** [comment]
Alright, then we can move forward with this.
The issue has been assigned to you

**Comment by CompetitiveRohan** [comment]
Sounds good! I'm on it. 😊

**Comment by CompetitiveRohan** [comment]
May I proceed with the same issue as before?

**Comment by jdwilkin4** [comment]
sure

**Comment by shootermv** [comment]
may be it can be better to have some kind of graphic design of this new feature
how it will look

**Comment by jdwilkin4** [comment]
I am going to close this again due to inactivity.

If you are interested in working on this in the future, then feel free to open and please provide a suggested design mockup so we can see your design implementation
