### ISSUE TITLE
Return answer given by user after answer submission 

### ISSUE THREAD

**Issue by erictleung** [freeCodeCamp/Developer_Quiz_Site#74]
When you finish a quiz question, the model returns your score and the correct answer.

However, at times, a user could be confident in their answer but end up getting their answer marked wrong and wonder what they initially put.

One thing to consider is the added room need to show this information, which would crowd the screen a bit more.

I'd imagine a solution would be something like:

> 💡 Correct! You are really good at this!
> Points: 1
> 
> Your answer:
> 
> mailfrom
> 
> Answer:
> 
> You can create a mailto link in the href value for an anchor tag
> Learn more with this helpful resource
> 
> Wanna learn how to code?
> Download the free Learn to Code RPG game

**Comment by jdwilkin4** [comment]
> One thing to consider is the added room need to show this information, which would crowd the screen a bit more.

I think this would work even if the answer was long like this
<img width="553" alt="Screen Shot 2022-07-01 at 7 42 55 PM" src="https://user-images.githubusercontent.com/67210629/176983807-9a9210a5-0c1c-4cbe-a3d5-99082efa531c.png">

Most of the answer aren't that long. And for the ones that are, the modal is large enough to accommodate the extra content IMO.
