### ISSUE TITLE
[Bug] - Buttons on the category page have text overflow on smaller screens

### ISSUE THREAD

**Issue by Bsodoge** [freeCodeCamp/Developer_Quiz_Site#747]
### What bug did you find in the codebase?

On mobile devices of screen size 439x667 downwards, text from buttons overflow outside the button as seen below with the accessibility and JavaScript buttons.

![image](https://github.com/freeCodeCamp/Developer_Quiz_Site/assets/79531561/3ed8e0db-e8d0-4a9e-9ab4-95d7f192b0e3)

The issue appears to be caused by a percentage width placed on the buttons container, a media query could be added to fix this issue.

I'd like to work to fix this issue, could you please assign it to me?

**Comment by jdwilkin4** [comment]
Good catch!
The issue has been assigned to you 👍
