### ISSUE TITLE
[Feature] - Add 10 more responses for incorrectModalResponses array

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/Developer_Quiz_Site#795]
### What feature would you like to see?

When a user gets a question wrong, then the modal pops up with a random incorrect modal response

<img width="582" alt="Screenshot 2023-10-11 at 12 36 35 PM" src="https://github.com/freeCodeCamp/Developer_Quiz_Site/assets/67210629/167fd908-787a-4f80-87ce-980345bf606f">

We want to add 10 more incorrect responses to the `incorrectModalResponses` array

Here is where the modal responses array lives
https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/main/src/data/modal-responses.ts

**Comment by tgmiller5** [comment]
Can I work on this issue?

**Comment by jdwilkin4** [comment]
it is all yours @tgmiller5

**Comment by Gautam-Hegde** [comment]
Any updates on the progress of this issue?

**Comment by tgmiller5** [comment]
This is being worked on.
