### ISSUE TITLE
Homepage design issues

### ISSUE THREAD

**Issue by ieahleen** [freeCodeCamp/Developer_Quiz_Site#85]
I went to the homepage and I was presented with this:

![image](https://user-images.githubusercontent.com/26656284/178447082-450ca5c7-3337-4dbf-b8a8-bba6345a7cb5.png)

Possible causes: I have an higer default font-size.

![image](https://user-images.githubusercontent.com/26656284/178447271-728560e8-8e77-4f2d-a818-be90f19fefca.png)

(It's the "Big" or "Large" setting, don't know how it is in English)

**Comment by jdwilkin4** [comment]
Yes, that was the cause. 
I was able to replicate this issue by temporally changing the font size settings
<img width="781" alt="Screen Shot 2022-07-12 at 11 39 10 AM" src="https://user-images.githubusercontent.com/67210629/178569694-d1f38378-f602-4248-8c7e-390df6432fdc.png">
