### ISSUE TITLE
[Feature] - Delay answers till a user clicks a submit button.

### ISSUE THREAD

**Issue by drvnprgrmr** [freeCodeCamp/Developer_Quiz_Site#850]
### What feature would you like to see?

The current flow reveals the result immediately an option is selected. 
I propose to add a button instead for submission while indicating the current option selected in the UI.

**Comment by jdwilkin4** [comment]
just to confirm, you are interested in working on this correct?

Or should I open it up for contribution?

**Comment by drvnprgrmr** [comment]
Yeah I intend on working on it.
