### ISSUE TITLE
[Feature] -Implementing color change for correct and wrong answers

### ISSUE THREAD

**Issue by Dimple-Choudhary** [freeCodeCamp/Developer_Quiz_Site#862]
### What feature would you like to see?

Feature:-
when clicking on the right answers makes the box turn green, and clicking on the wrong answers  makes it turn red.

@jdwilkin4  will you please  assign me this issue under hacktoberfest'23.

**Comment by jdwilkin4** [comment]
HI @Dimple-Choudhary ! 

We currently have this new feature here where there is a change in the flow and change in the buttons.
https://github.com/freeCodeCamp/Developer_Quiz_Site/pull/856

so, adding a new additional color I think would be to much in that situation, so we are not going to go with this suggestion at this time.

Thank you for your understanding
