### ISSUE TITLE
Enhancement: Test the question format

### ISSUE THREAD

**Issue by a2937** [freeCodeCamp/Developer_Quiz_Site#93]
I would like permission to test to see if the questions contain all the necessary data and if it is readable. Testing everything is generally important and I have enjoyed doing it for a side project for someone else.

**Comment by jdwilkin4** [comment]
> and if it is readable

Not sure what you mean by readable? 
Can you explain more on that? 
Thanks 👍

**Comment by a2937** [comment]
Basically I wanna ensure each question can be parsed. 

E.g Something like

```test.each(questionData)("Is a valid question", (input) =>
  {
    const sampleQuestion = { Question:"Some question" Answer:"Answer", Distractor1:"Distractor","Distractor2:"Distractor2",
    "Distractor3", Explanation:"Explanation", Link:"Link" };

    expect(input).toMatchObject<Question>(sampleQuestion);
  })```

**Comment by jdwilkin4** [comment]
sure, that would be fine 👍

**Comment by a2937** [comment]
I have an issue with this question:

https://github.com/freeCodeCamp/Developer_Quiz_Site/blob/68240da03236e6309f214050295d06b989b7713f/src/data/full-quiz.ts#L73-L83

There is a question with the property "Diatractor3" instead of "Distractor3". Should I put this into the same pull request as my test or fix it separately?
