### ISSUE TITLE
[Feature] - make selected answer yellow

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/Developer_Quiz_Site#965]
### currently the selected options is gray and the others is white(which looks wrong to me)
may be we can change it to opposite

like here:
![image](https://github.com/freeCodeCamp/Developer_Quiz_Site/assets/1336862/77e2f61f-bf7b-4473-bd17-990517be25b0)

**Comment by jdwilkin4** [comment]
I think the better option would be to just change the color of the selected answer from gray to something else like golden yellow so it pops more. 

<img width="943" alt="Screenshot 2024-06-18 at 6 18 56 AM" src="https://github.com/freeCodeCamp/Developer_Quiz_Site/assets/67210629/623d01e9-1f8e-4823-89d7-4d1470301dea">

**Comment by shootermv** [comment]
here is my opinion (im not designer, but i remember my teacher's comment from `design for web` class):
too many colors are bad,
 yellow color of selected option is totally looks `freecodecamp` style for me
 so - 
 if selected is yellow,
 may we can change color of sumbit to something like here:
 
![image](https://github.com/freeCodeCamp/Developer_Quiz_Site/assets/1336862/4397e27a-42e4-4b3f-bd83-cd2dbe94f6cc)
?

**Comment by jdwilkin4** [comment]
The submit button should still have some sort of hover state color change. 
But other then that, then this change works for me
