### ISSUE TITLE
[Bug] - inconsistent engine configuration

### ISSUE THREAD

**Issue by Gautam-Hegde** [freeCodeCamp/Developer_Quiz_Site#970]
### What bug did you find in the codebase?

  The main codebase uses the following engine config:
 ### 
  `"engines": {
    "node": ">=20",
    "pnpm": "9"
  },`
 ### But in Dockerfile the base image used is `18-alpine3.16`
  
![Screenshot (415)](https://github.com/freeCodeCamp/Developer_Quiz_Site/assets/85569489/7a712f09-f80c-482b-beee-b0edb7e90f69)

### app is not containerized properly missing global pnpm
![Screenshot (414)](https://github.com/freeCodeCamp/Developer_Quiz_Site/assets/85569489/acc03e6c-a962-4c27-b582-3a44541e5b7c)

I would like to take this issue.

**Comment by jdwilkin4** [comment]
sure, you can work on it
