### ISSUE TITLE
[Design] - change buttons width at mobile to be wider

### ISSUE THREAD

**Issue by shootermv** [freeCodeCamp/Developer_Quiz_Site#996]
### What bug did you find in the codebase?

i think it can be better to make the select  buttons to catch most of free space at mobile view:
![image](https://github.com/freeCodeCamp/Developer_Quiz_Site/assets/1336862/44d78d05-5de3-41bc-9822-6febdf751054)
instead of:
![image](https://github.com/freeCodeCamp/Developer_Quiz_Site/assets/1336862/86bde896-7f9d-4124-b4ce-c664a946b2a1)

**Comment by EdoriAtiri** [comment]
Hi @jdwilkin4 can this issue be assigned to me

**Comment by jdwilkin4** [comment]
@EdoriAtiri 

I marked this one as help wanted so anyone can work on it 👍
